
module Oscar where

import Everything
import Test

-- journals
import $RequiredForInstanceResolution
import AbstractStrictlyPositive
import AgdaErrorDisplayForm197
import AgdaFeatureInstanceResolutionViaConstraint
import AgdaFeatureNeedHiddenVariableTypeConstructorWrapper
import AgdaFeatureNoInstanceFromHidden
import AgdaFeaturePitfallInstanceResolution
import AgdaFeatureTerminationViaExplicitness
import AgdaIssue2557
import AgdaModuleEqualsSyntaxProblem
import AgdaSubstitute98Bug
import ExplicitInstanceSearchRequired
import MutualLevel
import NoEtaExpandedInstanceFromSuperclass
import NonuniqueUnification
import ReflexivityInFlexibility
import TroubleUnifyingExtensionalReflection
import UnificationIncompleteness
import UnificationRant
