
==============================================
Definition overwritten 5/30/2015     2:40:46
--------------------------------------------------------------------------------
(DEFUN MAKE-BACKWARDS-INFERENCE
       (REASON BINDING INTEREST DEPTH PRIORITY SUPPORTING-NODES CLUES
        INSTANTIATIONS SUPPOSITION
        &OPTIONAL GENERATING-NODE)
  (COND
   ((OR (BACKWARDS-PREMISES REASON) (BACKWARDS-PREMISES-FUNCTION REASON))
    (CONSTRUCT-INITIAL-INTEREST-LINK SUPPORTING-NODES INSTANTIATIONS REASON
                                     INTEREST DEPTH PRIORITY BINDING
                                     SUPPOSITION :GENERATING-NODE
                                     GENERATING-NODE :REMAINING-PREMISES
                                     (BACKWARDS-PREMISES REASON) :CLUES CLUES))
   ((OR (NUMBERP (REASON-STRENGTH REASON))
        (>= (FUNCALL (REASON-STRENGTH REASON) BINDING SUPPORTING-NODES)
            (DEGREE-OF-INTEREST INTEREST)))
    (DOLIST (P (FUNCALL (CONCLUSIONS-FUNCTION REASON) BINDING))
      (DRAW-CONCLUSION (CAR P) SUPPORTING-NODES REASON INSTANTIATIONS
                       (DISCOUNT-FACTOR REASON) DEPTH NIL (CDR P) :BINDING
                       BINDING :CLUES CLUES)))))
